In [1]:
#from IPython.core.display import HTML, display
import pandas as pd
import numpy as np

import matplotlib.pyplot as pl
import cartopy.crs as ccrs

In [2]:
#display(HTML("<style>.container {width: 90% !important}</style>"))

In [3]:
df = pd.read_pickle('./pickleJar/DevelopmentalDataSets/df_4_ML4aph.pkl')

In [ ]:
df.head().T

,0,1,2,3,4
oisst,19.57,2.54,0.78,1.79,24.67
etopo2,462,3549,330,2193,4369
solz,48.7,51.2,52.7,45.9,28
sat_rho_rc412,0.0120876,0.0105251,0.00444289,0.00586911,0.009464
sat_rho_rc443,0.0124167,0.0106362,0.00438667,0.00586578,0.008968
sat_rho_rc490,0.0117387,0.00961355,0.00424045,0.00553467,0.00771911
sat_rho_rc510,0.0105793,0.0079127,0.0036856,0.0046431,0.0059736
sat_rho_rc555,0.0091096,0.0062244,0.0026462,0.0033262,0.0041613
sat_rho_rc670,0.0066549,0.004794,0.0011773,0.0017469,0.0025167
datetime,1997-10-11 09:32:00,2000-02-22 17:00:00,2001-02-19 16:10:00,2002-01-22 13:45:00,1997-09-27 11:29:00
lat,39.29,-61.45,-61.29,-60.999,24.1392
lon,25.11,-62.299,-56.29,-56.498,-20.9995
aphy405,0,0,0.02149,0.01693,0
aphy411,0,0,0.0241,0.01886,0
aphy443,0,0,0.03078,0.02283,0
aphy455,0,0,0.02838,0.02071,0
aphy465,0,0,0.02765,0.01999,0
aphy489,0,0,0.02057,0.01464,0
aphy510,0,0,0.01261,0.00937,0
aphy520,0,0,0.00996,0.00756,0
aphy530,0,0,0.00776,0.006,0
aphy550,0,0,0.00448,0.0036,0
aphy555,0,0,0.00385,0.0031,0
aphy560,0,0,0.0034,0.00275,0
aphy565,0,0,0.0031,0.00252,0
aphy570,0,0,0.00291,0.00239,0
aphy590,0,0,0.00324,0.00282,0
aphy619,0,0,0.00328,0.00301,0
aphy625,0,0,0.00348,0.00319,0
aphy665,0,0,0.00774,0.00723,0
aphy670,0,0,0.0104,0.00935,0
aphy683,0,0,0.00949,0.00798,0

In [ ]:
subplot_kw = dict(projection=ccrs.PlateCarree())
f, ax = pl.subplots(figsize=(7, 11),
                   subplot_kw=subplot_kw)
#ax.background_patch.set_visible(False)
#ax.outline_patch.set_visible(False)
ax.stock_img()
ax.coastlines()
#ax.scatter(df.lon, df.lat)