In [1]:
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
import pandas as pd
from pandas.plotting import scatter_matrix
import numpy as np
import matplotlib.pyplot as pl
from matplotlib import rcParams
from seaborn import PairGrid, heatmap, kdeplot
import cmocean.cm as cmo

In [2]:
% matplotlib inline
rcParams['axes.titlesize'] = 18
rcParams['xtick.labelsize'] = 16
rcParams['ytick.labelsize'] = 16
rcParams['axes.labelsize'] = 16
rcParams['font.size'] = 16

In [3]:
df_pc = pd.read_pickle('./pickleJar/DevelopmentalDataSets/df_5_APHY_pc.pkl')
df_sat = pd.read_pickle('./pickleJar/DevelopmentalDataSets/df_5_APHY_sat')

In [4]:
df_pc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 495 entries, 0 to 494
Data columns (total 36 columns):
sin_doy         495 non-null float64
cos_doy         495 non-null float64
sin_minofday    495 non-null float64
cos_minofday    495 non-null float64
x               495 non-null float64
y               495 non-null float64
z               495 non-null float64
log10_etopo2    495 non-null float64
oisst           495 non-null float64
solz            495 non-null float64
PC1             494 non-null float64
PC2             494 non-null float64
PC3             494 non-null float64
PC4             494 non-null float64
PC5             494 non-null float64
PC6             494 non-null float64
aphy405         495 non-null float64
aphy411         495 non-null float64
aphy443         495 non-null float64
aphy455         495 non-null float64
aphy465         495 non-null float64
aphy489         495 non-null float64
aphy510         495 non-null float64
aphy520         495 non-null float64
aphy530         495 non-null float64
aphy550         495 non-null float64
aphy555         495 non-null float64
aphy560         495 non-null float64
aphy565         495 non-null float64
aphy570         495 non-null float64
aphy590         495 non-null float64
aphy619         495 non-null float64
aphy625         495 non-null float64
aphy665         495 non-null float64
aphy670         495 non-null float64
aphy683         495 non-null float64
dtypes: float64(36)
memory usage: 143.1 KB

In [5]:
df_sat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 495 entries, 0 to 494
Data columns (total 36 columns):
oisst            495 non-null float64
solz             495 non-null float64
sat_rho_rc412    495 non-null float64
sat_rho_rc443    495 non-null float64
sat_rho_rc490    495 non-null float64
sat_rho_rc510    495 non-null float64
sat_rho_rc555    495 non-null float64
sat_rho_rc670    495 non-null float64
aphy405          495 non-null float64
aphy411          495 non-null float64
aphy443          495 non-null float64
aphy455          495 non-null float64
aphy465          495 non-null float64
aphy489          495 non-null float64
aphy510          495 non-null float64
aphy520          495 non-null float64
aphy530          495 non-null float64
aphy550          495 non-null float64
aphy555          495 non-null float64
aphy560          495 non-null float64
aphy565          495 non-null float64
aphy570          495 non-null float64
aphy590          495 non-null float64
aphy619          495 non-null float64
aphy625          495 non-null float64
aphy665          495 non-null float64
aphy670          495 non-null float64
aphy683          495 non-null float64
log10_etopo2     495 non-null float64
sin_doy          495 non-null float64
cos_doy          495 non-null float64
sin_minofday     495 non-null float64
cos_minofday     495 non-null float64
x                495 non-null float64
y                495 non-null float64
z                495 non-null float64
dtypes: float64(36)
memory usage: 143.1 KB

In [6]:
df_pc = df_pc.loc[((df_pc.aphy411>0) & (df_pc.aphy443>0) & (df_pc.aphy489)
             & (df_pc.aphy510>0) & (df_pc.aphy555>0) & (df_pc.aphy670))
           ]

In [7]:
df_sat = df_sat.loc[((df_sat.aphy411>0) & (df_sat.aphy443>0) & (df_sat.aphy489)
             & (df_sat.aphy510>0) & (df_sat.aphy555>0) & (df_sat.aphy670))
           ]
df_sat = df_sat.loc[((df_sat.sat_rho_rc412>0) & (df_sat.sat_rho_rc443>0) & 
                    (df_sat.sat_rho_rc490>0) & (df_sat.sat_rho_rc510>0) &
                    (df_sat.sat_rho_rc555>0) & (df_sat.sat_rho_rc670>0))
                   ]

In [8]:
df_pc.loc[172:175].T

                       172        174           175
sin_doy      -8.359255e-01  -0.835925 -8.452491e-01
cos_doy      -5.488430e-01  -0.548843 -5.343726e-01
sin_minofday -9.807853e-01  -0.854912 -7.071068e-01
cos_minofday  1.950903e-01   0.518773 -7.071068e-01
x             1.036327e-01   0.101130  1.049779e-01
y            -8.824488e-01  -0.883359 -8.847049e-01
z             4.588512e-01   0.457657  4.541771e-01
log10_etopo2  1.518514e+00   1.623249  1.579784e+00
oisst         2.990000e+01  29.900000  2.990000e+01
solz          2.040000e+01  20.300000  1.810000e+01
PC1           4.217884e-02        NaN  3.859286e-02
PC2          -2.871977e-02        NaN -3.048090e-02
PC3          -2.021914e-04        NaN -1.518300e-03
PC4           3.094756e-03        NaN  1.890525e-03
PC5           8.899977e-04        NaN  1.330667e-03
PC6           2.003778e-17        NaN -3.761385e-18
aphy405       8.620000e-03   0.009810  8.210000e-03
aphy411       9.410000e-03   0.010850  8.860000e-03
aphy443       1.173000e-02   0.013950  1.084000e-02
aphy455       1.054000e-02   0.012820  9.590000e-03
aphy465       9.170000e-03   0.011380  8.400000e-03
aphy489       6.840000e-03   0.008310  6.510000e-03
aphy510       3.270000e-03   0.004030  3.340000e-03
aphy520       2.020000e-03   0.002450  2.200000e-03
aphy530       1.330000e-03   0.001560  1.650000e-03
aphy550       7.500000e-04   0.000810  1.130000e-03
aphy555       6.100000e-04   0.000650  9.100000e-04
aphy560       4.900000e-04   0.000500  6.900000e-04
aphy565       4.000000e-04   0.000410  5.300000e-04
aphy570       3.400000e-04   0.000350  4.000000e-04
aphy590       2.700000e-04   0.000300  2.000000e-04
aphy619       4.400000e-04   0.000470  3.700000e-04
aphy625       4.600000e-04   0.000510  4.200000e-04
aphy665       1.220000e-03   0.001430  1.370000e-03
aphy670       1.490000e-03   0.001790  1.770000e-03
aphy683       9.200000e-04   0.001100  1.210000e-03

In [9]:
df_sat.loc[172:175].T

                     172        175
oisst          29.900000  29.900000
solz           20.400000  18.100000
sat_rho_rc412   0.020585   0.018079
sat_rho_rc443   0.019720   0.017372
sat_rho_rc490   0.017998   0.016011
sat_rho_rc510   0.016039   0.014212
sat_rho_rc555   0.013809   0.012417
sat_rho_rc670   0.009977   0.009102
aphy405         0.008620   0.008210
aphy411         0.009410   0.008860
aphy443         0.011730   0.010840
aphy455         0.010540   0.009590
aphy465         0.009170   0.008400
aphy489         0.006840   0.006510
aphy510         0.003270   0.003340
aphy520         0.002020   0.002200
aphy530         0.001330   0.001650
aphy550         0.000750   0.001130
aphy555         0.000610   0.000910
aphy560         0.000490   0.000690
aphy565         0.000400   0.000530
aphy570         0.000340   0.000400
aphy590         0.000270   0.000200
aphy619         0.000440   0.000370
aphy625         0.000460   0.000420
aphy665         0.001220   0.001370
aphy670         0.001490   0.001770
aphy683         0.000920   0.001210
log10_etopo2    1.518514   1.579784
sin_doy        -0.835925  -0.845249
cos_doy        -0.548843  -0.534373
sin_minofday   -0.980785  -0.707107
cos_minofday    0.195090  -0.707107
x               0.103633   0.104978
y              -0.882449  -0.884705
z               0.458851   0.454177

In [11]:
df_pc.dropna(inplace=True)
df_sat.dropna(inplace=True)

In [12]:
df_pc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162 entries, 2 to 494
Data columns (total 36 columns):
sin_doy         162 non-null float64
cos_doy         162 non-null float64
sin_minofday    162 non-null float64
cos_minofday    162 non-null float64
x               162 non-null float64
y               162 non-null float64
z               162 non-null float64
log10_etopo2    162 non-null float64
oisst           162 non-null float64
solz            162 non-null float64
PC1             162 non-null float64
PC2             162 non-null float64
PC3             162 non-null float64
PC4             162 non-null float64
PC5             162 non-null float64
PC6             162 non-null float64
aphy405         162 non-null float64
aphy411         162 non-null float64
aphy443         162 non-null float64
aphy455         162 non-null float64
aphy465         162 non-null float64
aphy489         162 non-null float64
aphy510         162 non-null float64
aphy520         162 non-null float64
aphy530         162 non-null float64
aphy550         162 non-null float64
aphy555         162 non-null float64
aphy560         162 non-null float64
aphy565         162 non-null float64
aphy570         162 non-null float64
aphy590         162 non-null float64
aphy619         162 non-null float64
aphy625         162 non-null float64
aphy665         162 non-null float64
aphy670         162 non-null float64
aphy683         162 non-null float64
dtypes: float64(36)
memory usage: 46.8 KB

In [13]:
sat_cols = df_sat.columns.tolist()

In [14]:
sat_cols_new = [col for col in sat_cols if not col.startswith('aphy')] +\
                [col for col in sat_cols if col.startswith('aphy')]

In [15]:
df_sat = df_sat[sat_cols_new]

In [16]:
df_sat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162 entries, 2 to 494
Data columns (total 36 columns):
oisst            162 non-null float64
solz             162 non-null float64
sat_rho_rc412    162 non-null float64
sat_rho_rc443    162 non-null float64
sat_rho_rc490    162 non-null float64
sat_rho_rc510    162 non-null float64
sat_rho_rc555    162 non-null float64
sat_rho_rc670    162 non-null float64
log10_etopo2     162 non-null float64
sin_doy          162 non-null float64
cos_doy          162 non-null float64
sin_minofday     162 non-null float64
cos_minofday     162 non-null float64
x                162 non-null float64
y                162 non-null float64
z                162 non-null float64
aphy405          162 non-null float64
aphy411          162 non-null float64
aphy443          162 non-null float64
aphy455          162 non-null float64
aphy465          162 non-null float64
aphy489          162 non-null float64
aphy510          162 non-null float64
aphy520          162 non-null float64
aphy530          162 non-null float64
aphy550          162 non-null float64
aphy555          162 non-null float64
aphy560          162 non-null float64
aphy565          162 non-null float64
aphy570          162 non-null float64
aphy590          162 non-null float64
aphy619          162 non-null float64
aphy625          162 non-null float64
aphy665          162 non-null float64
aphy670          162 non-null float64
aphy683          162 non-null float64
dtypes: float64(36)
memory usage: 46.8 KB

In [17]:
df_pc.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_PC.pkl')
df_sat.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_SAT.pkl')

In [33]:
sc_pc = StandardScaler()
sc_pc_lim = StandardScaler()
sc_sat = StandardScaler()

In [35]:
X_s_pc = sc_pc.fit_transform(df_pc.loc[:, :'PC6'].values)
X_s_sat = sc_sat.fit_transform(df_sat.loc[:, :'z'].values)

In [37]:
X_s_pc_lim = sc_pc_lim.fit_transform(df_pc.loc[:, 'log10_etopo2': 'PC6'].values)

In [20]:
X_s_pc.shape, X_s_sat.shape

((162, 16), (162, 16))

In [38]:
feat_cols_pc_lim = df_pc.loc[:, 'log10_etopo2': 'PC6'].columns.tolist()
feat_cols_pc = df_pc.loc[:,:'PC6'].columns.tolist()
feat_cols_sat = df_sat.loc[:, :'z'].columns.tolist()
df_pc_s_lim = pd.DataFrame(X_s_pc_lim,
                           columns=['%s_s' % col for col in feat_cols_pc_lim],
                          index=df_pc.index)
df_pc_s = pd.DataFrame(X_s_pc, columns=['%s_s' % col for col in feat_cols_pc],
                       index=df_pc.index)
df_sat_s = pd.DataFrame(X_s_sat, columns=['%s_s' % col for col in feat_cols_sat],
                       index=df_sat.index)

In [39]:
df_pc_s_lim.head()

,log10_etopo2_s,oisst_s,solz_s,PC1_s,PC2_s,PC3_s,PC4_s,PC5_s,PC6_s
2,0.534148,-2.990826,1.429637,0.837503,0.532905,0.698848,2.162606,0.257826,1.669492
3,1.349502,-2.838796,0.974309,0.930459,0.275520,0.273833,1.103790,-0.454318,1.145318
26,1.649573,1.104955,-1.208586,2.652710,-0.475101,3.021028,-0.735825,-2.286466,2.324670
31,-0.826275,-2.102730,-0.264451,-1.364768,-1.397340,0.269219,-1.193771,-1.714171,0.537851
32,-1.016488,-1.503641,-0.612642,-1.273982,-0.867069,1.733866,-0.981065,-0.554956,-0.522603

In [22]:
df_pc_s.head()

,sin_doy_s,cos_doy_s,sin_minofday_s,cos_minofday_s,x_s,y_s,z_s,log10_etopo2_s,oisst_s,solz_s,PC1_s,PC2_s,PC3_s,PC4_s,PC5_s,PC6_s
2,0.741932,0.882889,-0.329893,-0.782974,0.545900,0.791444,-4.151014,0.534148,-2.990826,1.429637,0.837503,0.532905,0.698848,2.162606,0.257826,1.669492
3,0.217216,1.321747,0.729568,-1.637071,0.548743,0.778556,-4.143126,1.349502,-2.838796,0.974309,0.930459,0.275520,0.273833,1.103790,-0.454318,1.145318
26,-0.593027,-1.689420,-0.417725,-0.627779,0.837302,-0.221119,0.360438,1.649573,1.104955,-1.208586,2.652710,-0.475101,3.021028,-0.735825,-2.286466,2.324670
31,0.906276,-0.900850,-0.593966,0.251762,0.323005,-0.216655,0.652795,-0.826275,-2.102730,-0.264451,-1.364768,-1.397340,0.269219,-1.193771,-1.714171,0.537851
32,0.895061,-0.924717,-0.007875,-1.170834,0.330135,-0.237037,0.620325,-1.016488,-1.503641,-0.612642,-1.273982,-0.867069,1.733866,-0.981065,-0.554956,-0.522603

In [40]:
df_pc_s.shape, df_sat_s.shape, df_pc_s_lim.shape

((162, 16), (162, 16), (162, 9))

In [41]:
df_pc_s = pd.concat((df_pc_s, df_pc.filter(regex='aphy', axis=1)), axis=1)
df_pc_s_lim = pd.concat((df_pc_s_lim, df_pc.filter(regex='aphy', axis=1)), axis=1)

In [42]:
df_pc_s.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162 entries, 2 to 494
Data columns (total 36 columns):
sin_doy_s         162 non-null float64
cos_doy_s         162 non-null float64
sin_minofday_s    162 non-null float64
cos_minofday_s    162 non-null float64
x_s               162 non-null float64
y_s               162 non-null float64
z_s               162 non-null float64
log10_etopo2_s    162 non-null float64
oisst_s           162 non-null float64
solz_s            162 non-null float64
PC1_s             162 non-null float64
PC2_s             162 non-null float64
PC3_s             162 non-null float64
PC4_s             162 non-null float64
PC5_s             162 non-null float64
PC6_s             162 non-null float64
aphy405           162 non-null float64
aphy411           162 non-null float64
aphy443           162 non-null float64
aphy455           162 non-null float64
aphy465           162 non-null float64
aphy489           162 non-null float64
aphy510           162 non-null float64
aphy520           162 non-null float64
aphy530           162 non-null float64
aphy550           162 non-null float64
aphy555           162 non-null float64
aphy560           162 non-null float64
aphy565           162 non-null float64
aphy570           162 non-null float64
aphy590           162 non-null float64
aphy619           162 non-null float64
aphy625           162 non-null float64
aphy665           162 non-null float64
aphy670           162 non-null float64
aphy683           162 non-null float64
dtypes: float64(36)
memory usage: 46.8 KB

In [43]:
df_pc_s_lim.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162 entries, 2 to 494
Data columns (total 29 columns):
log10_etopo2_s    162 non-null float64
oisst_s           162 non-null float64
solz_s            162 non-null float64
PC1_s             162 non-null float64
PC2_s             162 non-null float64
PC3_s             162 non-null float64
PC4_s             162 non-null float64
PC5_s             162 non-null float64
PC6_s             162 non-null float64
aphy405           162 non-null float64
aphy411           162 non-null float64
aphy443           162 non-null float64
aphy455           162 non-null float64
aphy465           162 non-null float64
aphy489           162 non-null float64
aphy510           162 non-null float64
aphy520           162 non-null float64
aphy530           162 non-null float64
aphy550           162 non-null float64
aphy555           162 non-null float64
aphy560           162 non-null float64
aphy565           162 non-null float64
aphy570           162 non-null float64
aphy590           162 non-null float64
aphy619           162 non-null float64
aphy625           162 non-null float64
aphy665           162 non-null float64
aphy670           162 non-null float64
aphy683           162 non-null float64
dtypes: float64(29)
memory usage: 38.0 KB

In [44]:
df_sat_s = pd.concat((df_sat_s, df_sat.filter(regex='aphy', axis=1)), axis=1)

In [45]:
pf_pc_lim = PolynomialFeatures(interaction_only=True, include_bias=False)
pf_pc = PolynomialFeatures(interaction_only=True, include_bias=False)
pf_sat = PolynomialFeatures(interaction_only=True, include_bias=False)

In [46]:
Xsp_pc_lim = pf_pc_lim.fit_transform(X_s_pc_lim)
Xsp_pc = pf_pc.fit_transform(X_s_pc)
Xsp_sat = pf_sat.fit_transform(X_s_sat)

In [47]:
y_aphy = df_pc.filter(regex='aphy', axis=1)

In [48]:
y_aphy.shape

(162, 20)

In [49]:
pf_nams_pc_lim = pf_pc_lim.get_feature_names(input_features=df_pc_s_lim.loc[:,:'PC6_s'].columns)
poly_df_cols_pc_lim = pf_nams_pc_lim + y_aphy.columns.tolist()
poly_feat_nams_pc = pf_pc.get_feature_names(input_features=df_pc_s.loc[:,:'PC6_s'].columns)
poly_df_cols_pc = poly_feat_nams_pc + y_aphy.columns.tolist()
poly_feat_nams_sat = pf_pc.get_feature_names(input_features=df_sat_s.loc[:,:'z_s'].columns)
poly_df_cols_sat = poly_feat_nams_sat + y_aphy.columns.tolist()

In [51]:
df_sp_pc_lim = pd.DataFrame(np.c_[Xsp_pc_lim, y_aphy], columns=poly_df_cols_pc_lim,
                           index=df_pc_s_lim.index)

In [53]:
df_sp_pc = pd.DataFrame(np.c_[Xsp_pc, y_aphy], columns=poly_df_cols_pc,
                        index=df_pc_s.index)

In [54]:
df_sp_sat = pd.DataFrame(np.c_[Xsp_sat, y_aphy], columns=poly_df_cols_sat,
                        index=df_sat_s.index)

In [55]:
df_sp_pc.shape, df_sp_sat.shape, df_sp_pc_lim.shape

((162, 156), (162, 156), (162, 65))

In [56]:
df_pc_s_lim.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_PC_lim.pkl')
df_sp_pc_lim.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_PC_lim.pkl')
df_pc_s.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PC.pkl')
df_sp_pc.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_PC.pkl')
df_sat_s.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_SAT.pkl')
df_sp_sat.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_SAT.pkl')

In [57]:
aphys = ['aphy411', 'aphy443', 'aphy489', 'aphy510', 'aphy555', 'aphy670']
df_s_SWF_pc = pd.concat((df_pc_s.loc[:, :'PC6_s'], df_pc_s[aphys]), axis=1)
df_s_SWF_pc_lim = pd.concat((df_pc_s_lim.loc[:, :'PC6_s'], df_pc_s_lim[aphys]), axis=1)
df_s_SWF_sat = pd.concat((df_sat_s.loc[:, :'z_s'], df_sat_s[aphys]), axis=1)

In [52]:
df_sp_sat.head().T

,2,3,26,31,32
oisst_s,-2.990826,-2.838796,1.104955,-2.102730,-1.503641
solz_s,1.429637,0.974309,-1.208586,-0.264451,-0.612642
sat_rho_rc412_s,-0.731412,-0.388146,1.069547,-0.445053,-0.093121
sat_rho_rc443_s,-0.878914,-0.498733,0.686661,-0.331946,-0.023906
sat_rho_rc490_s,-1.034350,-0.687684,-0.188815,-0.230660,0.166008
sat_rho_rc510_s,-1.008665,-0.748061,-0.701193,0.101169,0.517129
sat_rho_rc555_s,-1.033670,-0.855011,-0.913337,0.685269,1.199755
sat_rho_rc670_s,-0.980192,-0.764523,-0.774216,0.735696,0.697833
log10_etopo2_s,0.534148,1.349502,1.649573,-0.826275,-1.016488
sin_doy_s,0.741932,0.217216,-0.593027,0.906276,0.895061
cos_doy_s,0.882889,1.321747,-1.689420,-0.900850,-0.924717
sin_minofday_s,-0.329893,0.729568,-0.417725,-0.593966,-0.007875
cos_minofday_s,-0.782974,-1.637071,-0.627779,0.251762,-1.170834
x_s,0.545900,0.548743,0.837302,0.323005,0.330135
y_s,0.791444,0.778556,-0.221119,-0.216655,-0.237037
z_s,-4.151014,-4.143126,0.360438,0.652795,0.620325
oisst_s solz_s,-4.275796,-2.765865,-1.335433,0.556068,0.921194
oisst_s sat_rho_rc412_s,2.187526,1.101866,1.181801,0.935825,0.140021
oisst_s sat_rho_rc443_s,2.628678,1.415800,0.758729,0.697993,0.035947
oisst_s sat_rho_rc490_s,3.093562,1.952194,-0.208632,0.485015,-0.249616
oisst_s sat_rho_rc510_s,3.016743,2.123593,-0.774787,-0.212731,-0.777576
oisst_s sat_rho_rc555_s,3.091527,2.427201,-1.009196,-1.440935,-1.804000
oisst_s sat_rho_rc670_s,2.931585,2.170325,-0.855473,-1.546971,-1.049290
oisst_s log10_etopo2_s,-1.597543,-3.830962,1.822704,1.737433,1.528433
oisst_s sin_doy_s,-2.218989,-0.616632,-0.655268,-1.905654,-1.345850
oisst_s cos_doy_s,-2.640566,-3.752171,-1.866732,1.894244,1.390442
oisst_s sin_minofday_s,0.986652,-2.071096,-0.461567,1.248950,0.011841
oisst_s cos_minofday_s,2.341740,4.647311,-0.693667,-0.529387,1.760514
oisst_s x_s,-1.632692,-1.557768,0.925181,-0.679193,-0.496405
oisst_s y_s,-2.367070,-2.210163,-0.244326,0.455567,0.356418
...,...,...,...,...,...
sin_minofday_s cos_minofday_s,0.258298,-1.194355,0.262239,-0.149538,0.009220
sin_minofday_s x_s,-0.180088,0.400345,-0.349762,-0.191854,-0.002600
sin_minofday_s y_s,-0.261091,0.568010,0.092367,0.128686,0.001867
sin_minofday_s z_s,1.369389,-3.022694,-0.150564,-0.387738,-0.004885
cos_minofday_s x_s,-0.427426,-0.898331,-0.525640,0.081320,-0.386534
cos_minofday_s y_s,-0.619680,-1.274552,0.138814,-0.054545,0.277531
cos_minofday_s z_s,3.250137,6.782592,-0.226275,0.164349,-0.726298
x_s y_s,0.432049,0.427227,-0.185143,-0.069981,-0.078254
x_s z_s,-2.266038,-2.273510,0.301796,0.210856,0.204791
y_s z_s,-3.285294,-3.225657,-0.079700,-0.141431,-0.147040
aphy405,0.021490,0.016930,0.001800,0.445490,0.067190
aphy411,0.024100,0.018860,0.001990,0.476540,0.073380
aphy443,0.030780,0.022830,0.002560,0.540020,0.077990
aphy455,0.028380,0.020710,0.002470,0.442710,0.064220
aphy465,0.027650,0.019990,0.002360,0.383020,0.060670
aphy489,0.020570,0.014640,0.001810,0.285550,0.045400
aphy510,0.012610,0.009370,0.001030,0.207310,0.034530
aphy520,0.009960,0.007560,0.000760,0.155640,0.026760
aphy530,0.007760,0.006000,0.000570,0.120300,0.020530
aphy550,0.004480,0.003600,0.000350,0.071100,0.010820
aphy555,0.003850,0.003100,0.000310,0.062940,0.008960
aphy560,0.003400,0.002750,0.000280,0.059940,0.007140
aphy565,0.003100,0.002520,0.000260,0.062090,0.005580
aphy570,0.002910,0.002390,0.000260,0.067930,0.004860
aphy590,0.003240,0.002820,0.000260,0.082120,0.005580
aphy619,0.003280,0.003010,0.000240,0.121670,0.007310
aphy625,0.003480,0.003190,0.000240,0.129760,0.008110
aphy665,0.007740,0.007230,0.000450,0.333810,0.033440
aphy670,0.010400,0.009350,0.000560,0.354500,0.041170
aphy683,0.009490,0.007980,0.000450,0.195130,0.032940

In [58]:
df_sp_SWF_pc_lim = pd.concat((df_sp_pc_lim.loc[:, :'PC5_s PC6_s'], 
                              df_sp_pc_lim[aphys]), axis=1)
df_sp_SWF_pc = pd.concat((df_sp_pc.loc[:, :'PC5_s PC6_s'], df_sp_pc[aphys]), axis=1)
df_sp_SWF_sat = pd.concat((df_sp_sat.loc[:, :'y_s z_s'], df_sp_sat[aphys]), axis=1)

In [60]:
df_s_SWF_pc_lim.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_SWF_PC_lim.pkl')
df_s_SWF_pc.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_SWF_PC.pkl')
df_s_SWF_sat.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_SWF_SAT.pkl')
df_sp_SWF_pc_lim.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_SWF_PC_lim.pkl')
df_sp_SWF_pc.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_SWF_PC.pkl')
df_sp_SWF_sat.to_pickle('./pickleJar/OperationalDataSets/df_6_APHY_Standardized_PolyFeatures_SWF_SAT.pkl')